from __future__ import annotations

from sim2real.config.robots.base import RobotCfg

JAKA_JOINT_NAMES = (
    "Left_hip_pitch_joint",
    "Left_hip_roll_joint",
    "Left_hip_yaw_joint",
    "Left_knee_joint",
    "Left_ankle_pitch_joint",
    "Left_ankle_roll_joint",
    "Right_hip_pitch_joint",
    "Right_hip_roll_joint",
    "Right_hip_yaw_joint",
    "Right_knee_joint",
    "Right_ankle_pitch_joint",
    "Right_ankle_roll_joint",
    "waist_yaw_joint",
    "Left_shoulder_pitch_joint",
    "Left_shoulder_roll_joint",
    "Left_shoulder_yaw_joint",
    "Left_elbow_joint",
    "Left_wrist_roll_joint",
    "Left_wrist_yaw_joint",
    "Right_shoulder_pitch_joint",
    "Right_shoulder_roll_joint",
    "Right_shoulder_yaw_joint",
    "Right_elbow_joint",
    "Right_wrist_roll_joint",
    "Right_wrist_yaw_joint",
    "Neck_yaw_joint",
    "Neck_pitch_joint",
)

JAKA_BODY_NAMES = (
    "base_link",
    "Left_hip_pitch_Link",
    "Left_hip_roll_Link",
    "Left_hip_yaw_Link",
    "Left_knee_Link",
    "Left_ankle_pitch_Link",
    "Left_ankle_roll_Link",
    "Right_hip_pitch_Link",
    "Right_hip_roll_Link",
    "Right_hip_yaw_Link",
    "Right_knee_Link",
    "Right_ankle_pitch_Link",
    "Right_ankle_roll_Link",
    "waist_yaw_Link",
    "Left_shoulder_pitch_Link",
    "Left_shoulder_roll_Link",
    "Left_shoulder_yaw_Link",
    "Left_elbow_Link",
    "Left_wrist_roll_Link",
    "Left_wrist_yaw_Link",
    "Right_shoulder_pitch_Link",
    "Right_shoulder_roll_Link",
    "Right_shoulder_yaw_Link",
    "Right_elbow_Link",
    "Right_wrist_roll_Link",
    "Right_wrist_yaw__Link",
    "Neck_yaw_Link",
    "Neck_pitch_Link",
)

JAKA_CFG = RobotCfg(
    name="jaka",
    joint_names=JAKA_JOINT_NAMES,
    body_names=JAKA_BODY_NAMES,
    joint_pos_lower_limit={
        "Left_hip_pitch_joint": -1.9198,
        "Left_hip_roll_joint": -0.5236,
        "Left_hip_yaw_joint": -2.0071,
        "Left_knee_joint": -0.349,
        "Left_ankle_pitch_joint": -0.5236,
        "Left_ankle_roll_joint": -0.349,
        "Right_hip_pitch_joint": -1.9198,
        "Right_hip_roll_joint": -0.5236,
        "Right_hip_yaw_joint": -2.0071,
        "Right_knee_joint": -0.349,
        "Right_ankle_pitch_joint": -0.5236,
        "Right_ankle_roll_joint": -0.349,
        "waist_yaw_joint": -2.0071,
        "Left_shoulder_pitch_joint": -1.5707,
        "Left_shoulder_roll_joint": -1.9189,
        "Left_shoulder_yaw_joint": -1.5707,
        "Left_elbow_joint": -0.8726,
        "Left_wrist_roll_joint": -1.5707,
        "Left_wrist_yaw_joint": 0.0,
        "Right_shoulder_pitch_joint": -1.5707,
        "Right_shoulder_roll_joint": -1.9189,
        "Right_shoulder_yaw_joint": -1.5707,
        "Right_elbow_joint": -0.8726,
        "Right_wrist_roll_joint": -1.5707,
        "Right_wrist_yaw_joint": 0.0,
        "Neck_yaw_joint": -1.5707,
        "Neck_pitch_joint": -0.6108,
    },
    joint_pos_upper_limit={
        "Left_hip_pitch_joint": 1.2217,
        "Left_hip_roll_joint": 2.3562,
        "Left_hip_yaw_joint": 3.5779,
        "Left_knee_joint": 2.2689,
        "Left_ankle_pitch_joint": 0.6108,
        "Left_ankle_roll_joint": 0.349,
        "Right_hip_pitch_joint": 1.2217,
        "Right_hip_roll_joint": 3.5779,
        "Right_hip_yaw_joint": 3.5779,
        "Right_knee_joint": 2.2689,
        "Right_ankle_pitch_joint": 0.6108,
        "Right_ankle_roll_joint": 0.349,
        "waist_yaw_joint": 3.5779,
        "Left_shoulder_pitch_joint": 1.5707,
        "Left_shoulder_roll_joint": 1.9189,
        "Left_shoulder_yaw_joint": 1.5707,
        "Left_elbow_joint": 2.2689,
        "Left_wrist_roll_joint": 1.5707,
        "Left_wrist_yaw_joint": 1.5707,
        "Right_shoulder_pitch_joint": 1.5707,
        "Right_shoulder_roll_joint": 1.9189,
        "Right_shoulder_yaw_joint": 1.5707,
        "Right_elbow_joint": 2.2689,
        "Right_wrist_roll_joint": 1.5707,
        "Right_wrist_yaw_joint": 1.5707,
        "Neck_yaw_joint": 1.5707,
        "Neck_pitch_joint": 0.6108,
    },
    joint_velocity_limit={name: 30.0 for name in JAKA_JOINT_NAMES},
    joint_effort_limit={
        "Left_hip_pitch_joint": 120.0,
        "Left_hip_roll_joint": 120.0,
        "Left_hip_yaw_joint": 120.0,
        "Left_knee_joint": 120.0,
        "Left_ankle_pitch_joint": 96.0,
        "Left_ankle_roll_joint": 96.0,
        "Right_hip_pitch_joint": 120.0,
        "Right_hip_roll_joint": 120.0,
        "Right_hip_yaw_joint": 120.0,
        "Right_knee_joint": 120.0,
        "Right_ankle_pitch_joint": 96.0,
        "Right_ankle_roll_joint": 96.0,
        "waist_yaw_joint": 120.0,
        "Left_shoulder_pitch_joint": 96.0,
        "Left_shoulder_roll_joint": 96.0,
        "Left_shoulder_yaw_joint": 36.0,
        "Left_elbow_joint": 36.0,
        "Left_wrist_roll_joint": 8.0,
        "Left_wrist_yaw_joint": 8.0,
        "Right_shoulder_pitch_joint": 96.0,
        "Right_shoulder_roll_joint": 96.0,
        "Right_shoulder_yaw_joint": 36.0,
        "Right_elbow_joint": 36.0,
        "Right_wrist_roll_joint": 8.0,
        "Right_wrist_yaw_joint": 8.0,
        "Neck_yaw_joint": 8.0,
        "Neck_pitch_joint": 8.0,
    },
    joint_armature={
        "Left_hip_pitch_joint": 0.03,
        "Left_hip_roll_joint": 0.03,
        "Left_hip_yaw_joint": 0.03,
        "Left_knee_joint": 0.03,
        "Left_ankle_pitch_joint": 0.016,
        "Left_ankle_roll_joint": 0.016,
        "Right_hip_pitch_joint": 0.03,
        "Right_hip_roll_joint": 0.03,
        "Right_hip_yaw_joint": 0.03,
        "Right_knee_joint": 0.03,
        "Right_ankle_pitch_joint": 0.016,
        "Right_ankle_roll_joint": 0.016,
        "waist_yaw_joint": 0.03,
        "Left_shoulder_pitch_joint": 0.016,
        "Left_shoulder_roll_joint": 0.016,
        "Left_shoulder_yaw_joint": 0.01,
        "Left_elbow_joint": 0.01,
        "Left_wrist_roll_joint": 0.01,
        "Left_wrist_yaw_joint": 0.01,
        "Right_shoulder_pitch_joint": 0.016,
        "Right_shoulder_roll_joint": 0.016,
        "Right_shoulder_yaw_joint": 0.01,
        "Right_elbow_joint": 0.01,
        "Right_wrist_roll_joint": 0.01,
        "Right_wrist_yaw_joint": 0.01,
        "Neck_yaw_joint": 0.01,
        "Neck_pitch_joint": 0.01,
    },
    joint_frictionloss={name: 0.01 for name in JAKA_JOINT_NAMES},
    mjcf_path="jaka_data/Khan_mini_simplified/Khan_mini_simplified_new_bigfeet.xml",
    default_qpos=(
        0.0, 0.0, 0.793, 1.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0,
        0.0, -1.57, 0.0, 1.57, 0.0, 0.3,
        0.0, -1.57, 0.0, 1.57, 0.0, 0.3,
        0.0, 0.0
    ),
    root_joint_names=("base_joint", "floating_base_joint", "pelvis_root"),
    viewer_track_body_names=("base_link",),
    elastic_band_attach_body_names=("waist_yaw_Link", "base_link"),
)
